#!/usr/bin/zsh

rm -rf ~/.vim/bundle/nerdtree
rm -rf ~/.vim/pack/tpope/start
git clone https://github.com/preservim/nerdtree.git ~/.vim/bundle/nerdtree
mkdir -p ~/.vim/pack/tpope/start
cd ~/.vim/pack/tpope/start
git clone https://tpope.io/vim/commentary.git
vim -u NONE -c "helptags commentary/doc" -c q

cp vimrc ~/.vimrc

./install-dev-java
./install-dev-node

# sublime

wget -qO - https://download.sublimetext.com/sublimehq-pub.gpg | sudo apt-key add -
echo "deb https://download.sublimetext.com/ apt/stable/" | sudo tee /etc/apt/sources.list.d/sublime-text.list
sudo apt update
sudo apt -y install sublime-text
