#!/usr/bin/zsh

# bumblebee
sudo apt -y install python3-pip python-setuptools fonts-font-awesome
mkdir -p ~/.config/i3/tools/
pip3 install --user bumblebee-status
mv ~/.local/bin/bumblebee-status ~/.config/i3/tools/

# rofi
sudo apt -y install rofi

# i3
mkdir -p ~/.config/i3/
cp i3-config ~/.config/i3/config

# niceties
sudo apt -y install nitrogen compton
mkdir -p ~/.config/nitrogen
cp nitrogen.cfg ~/.config/nitrogen/
cp bg-saved.cfg ~/.config/nitrogen/ 
cp compton.conf ~/.config/compton.conf

i3-msg restart
