#!/usr/bin/zsh

git clone https://github.com/preservim/nerdtree.git ~/.vim/bundle/nerdtree
mkdir -p ~/.vim/pack/tpope/start
cd ~/.vim/pack/tpope/start
git clone https://tpope.io/vim/commentary.git
vim -u NONE -c "helptags commentary/doc" -c q

./install-dev-java
./install-dev-node

