#!/usr/bin/zsh

# install scala

if ! type "sbt"; then
  echo "deb https://dl.bintray.com/sbt/debian /" | sudo tee -a /etc/apt/sources.list.d/sbt.list
  curl -sL "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x2EE0EA64E40A89B84B2DF73499E82A75642AC823" | sudo apt-key add
  sudo apt update
  sudo apt install sbt
fi

# install haskell
sudo apt install haskell-platform

