#!/usr/bin/zsh

# file manager
sudo apt -y install ranger

# applications: print screen
sudo apt -y install scrot viewnior
mkdir -p ~/pictures/

# chrome
if ! type "google-chrome"; then
  wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  sudo apt install ./google-chrome-stable_current_amd64.deb
  rm ./google-chrome-stable_current_amd64.deb
fi

